package main

import (
	"fmt"
	"piscine"
)

func main() {
	fmt.Println("QuadA >>>>")
	fmt.Println()
	piscine.QuadA(5, 3)
	fmt.Println()
	piscine.QuadA(5, 1)
	fmt.Println()
	piscine.QuadA(1, 1)
	fmt.Println()
	piscine.QuadA(1, 5)
	fmt.Println()
	fmt.Println("QuadB >>>>")
	fmt.Println()
	piscine.QuadB(5, 3)
	fmt.Println()
	piscine.QuadB(5, 1)
	fmt.Println()
	piscine.QuadB(1, 1)
	fmt.Println()
	piscine.QuadB(1, 5)
	fmt.Println()
	fmt.Println("QuadC >>>>")
	fmt.Println()
	piscine.QuadC(5, 3)
	fmt.Println()
	piscine.QuadC(5, 1)
	fmt.Println()
	piscine.QuadC(1, 1)
	fmt.Println()
	piscine.QuadC(1, 5)
	fmt.Println()
	fmt.Println("QuadD >>>>")
	fmt.Println()
	piscine.QuadD(5, 3)
	fmt.Println()
	piscine.QuadD(5, 1)
	fmt.Println()
	piscine.QuadD(1, 1)
	fmt.Println()
	piscine.QuadD(1, 5)
	fmt.Println()
	fmt.Println("QuadE >>>>")
	fmt.Println()
	piscine.QuadE(5, 3)
	fmt.Println()
	piscine.QuadE(5, 1)
	fmt.Println()
	piscine.QuadE(1, 1)
	fmt.Println()
	piscine.QuadE(1, 5)
}
